### ISSUE TITLE
Bears content role configuration

### ISSUE THREAD

**Issue by gchi25** [GSA/px-bears-drupal#121]

**Comment by gchi25** [comment]
Implement Bears content role and permission.
Export the role configuration.

**Comment by EnriqueOrt** [comment]
Waiting on some information from @fongcindy - Gene will follow up.

**Comment by fongcindy** [comment]
7/18: 
Next steps: 
- Create a content workflow for BEARS (based on the usa.gov current content workflow) 
- Create account for Diego, Ernie, Cindy for content entry and management in sandbox with the BEARS content workflow.
- Run drush uli for Diego, Ernie, Cindy for now, eventually we will be able to login the sandbox as administrator and can modify/edit BEARS content.

**Comment by scottqueen-bixal** [comment]
When @FatmaBakir returns, we will update sandbox database, code, and config - at which time we can set this configuration.
