### ISSUE TITLE
Organize UI Template Content (Translations)

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-bears-drupal#213]
We will need to create locale content that will be managed in the application as part of the templates for both EN and ES.

1. Identify which parts of the application will need translations
2. Create a JSON object with keys and EN value pairs
3. include ES translations

**Comment by scottqueen-bixal** [comment]
1. Identify which parts of the application will need translations

![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/4cbbb0a7-6ce5-4be9-b1d0-3ae7a3a7f646)
![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/dd12c8e3-62e6-47de-a442-ddf5189cb960)

This part of the process is complete, we will move on to converting these into a JSON structure for step 2.

**Comment by EnriqueOrt** [comment]
https://docs.google.com/document/d/1wt3hIA6vd6XuiS5XCkY5YhMLxysawxu-lnTvAytt2VA/edit
