### ISSUE TITLE
Automate JSON data rebuilding

### ISSUE THREAD

**Issue by gchi25** [GSA/px-bears-drupal#394]
Automate JSON data rebuilding

1. Update JSON data when insert/update/delete benefits content
2. Generate JSON data file
3. Assign the JSON data file to Life Event JSON data file field

**Comment by scottqueen-bixal** [comment]
**drafts, versions** will trigger drupal content to rebuild json file at /draft/file name.json (TOME DO NOT BUILD)
**published** version trigger drupal content to rebuild json file at /published/file name.json (TOME BUILD)

path is in twig template, JS app will fetch on load

**Comment by scottqueen-bixal** [comment]
Status: 25%

Need custom code development in module
