### ISSUE TITLE
Create BEARS Requirements

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-bears-drupal#47]
- [x] Create and compile BEARS feature & functional [requirements](https://docs.google.com/document/d/1o3uIgU6eHqTX4PSMXv4Kv1ILokx13zPy/edit). 
- [ ] Create content section of requirements

**Comment by diegocob** [comment]
Hi @fongcindy, could you please share what this is referring to? Maybe we were using different wording or I don't recall. Are these all the new sections for content on v2?

**Comment by diegocob** [comment]
Hi Cindy,
I think this is reviewed from my end - at the high level I understood was
needed. Please let me know if you had something else in mind.

Best,
Diego

**Comment by diegocob** [comment]
@fongcindy, is there anything else I should do on my end on this?

**Comment by fongcindy** [comment]
Hi Diego, no actions on your end, thanks for checking on this though!
