### ISSUE TITLE
a11y | radio labels

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-bears-drupal#511]
14 | 08/31 | Amy | Radio button labels need more clear labels | A user using assistive tech will need to know if they’re selecting yes or no without seeing the word yes or no. | It’s hard to tell but does the radio button announce yes or no?This technique is Advisory for 1.3.1: Info and Relationships and Sufficient to meet 3.3.2: Labels or Instructions when used with G131: Providing descriptive labels. | I used ANDI (free applet) to view the labels. Some labels appear on the page and others can be added to the code. | See screen shot. | Development | Blank |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by amycole501** [comment]
I can hear "yes" and "no" now and ANDI indicates that the wording is there:
![image](https://github.com/GSA/px-bears-drupal/assets/117778073/c6484ab5-3245-4e15-b24d-35440abdf73e)

**Comment by amycole501** [comment]
The only issue I can find is that the arrow keys don't allow me to toggle between "yes" and "no" when the group is activated.

https://www.w3.org/wiki/RadioButton#:~:text=Up%20Arrow%20key%20press%20moves,radio%20buttons%20in%20the%20group.
