### ISSUE TITLE
a11y | date input labels

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-bears-drupal#531]
8 | 1-High | about the applicant |   |   | unclear wording in the numeral fields. The year says "year edit, has popup. Type in text" | In the image to the left I hear "type in text. Has popup" which is weird and confusing. It says type in text but not "enter numerals for day"
-- | -- | -- | -- | -- | -- | --

<google-sheets-html-origin><style type="text/css"></style>

9 | 1-High | about the applicant | see image attached |

![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/5f6737ad-3b06-4558-87a2-7dc5298bc958)

**Comment by amycole501** [comment]
When I load this page https://bears-storybook.app.cloud.gov/iframe.html?id=app--primary&viewMode=story the first thing I hear in JAWS and NVDA is the error status message.
This video recording will help: https://app.screencast.com/LiikaTfL95cMy

**Comment by amycole501** [comment]
Regarding the labels:
1. The form labels are visible and persistent
2. The form field(s) are heard to be required and the visible label above shows the fields are required
3. If I tab to the first  "month" field, the first thing I hear is "invalid entry" before I choose a month. Can that be removed? it seems like it's defaulting to check the state of the dropdown before I get a chance to select anything.
