### ISSUE TITLE
a11y | error handling date field

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-bears-drupal#532]
10 | 1-High | about the applicant |   |   |   | I don't get any clear error handling when typing in a single digit for a year.
-- | -- | -- | -- | -- | -- | --

![Image](https://user-images.githubusercontent.com/37077057/268040981-318f03ea-bc66-4708-a274-6007ed5bd686.png)

**Comment by amycole501** [comment]
The error handling is improved; the date example is clearly shown. While improved, we could see an area for further improvement by which the date field has its own error message for example "Year must have four digits". We still need to listen to the date in JAWS. That review is coming soon.

**Comment by amycole501** [comment]
Using JAWS I heard "error status" announced twice. Example:
"error status. Error status" then it reads the error message for the required fields. I also hear "error status. Error status" then the error message for the proper date entry.

1. Remove one of the "error status" announcements in each of the error messages to remove redundancy.
2. 
![image](https://github.com/GSA/px-bears-drupal/assets/117778073/27d8b61c-2af5-4047-a032-399016337609)
Add the word "four" in the help text. "Enter **four** numerals for year'.
3. The error message should clearly describe the errors presented and how to fix them. For example, "Enter a valid year" is not as helpful as "Year must be a four digit number". 

If the person made more than one mistake in the DOB field, it would be helpful to inform the user how many errors were detected.
