### ISSUE TITLE
design audit review | Critical

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-bears-drupal#574]
This ticket is to track work marked as `Severity Rating: 2` from the design audit

https://docs.google.com/document/d/1Tgr4ccDpJjDVCTfXaRyqSpet-Fmv0bTD3qVX9_4F7v4/edit

**Comment by scottqueen-bixal** [comment]
From the document there was only one `Severity Rating:  2` noted.

This work was updated in previous audit feedback from a11y.



![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/fb7a6483-131b-45aa-9077-9b718e950cbc)

@nehemiah-abuga tagging you for review and confirmation.

**Comment by ErnestoFernandezAlvarez** [comment]
Thanks @gscottqueen I see the changes you made.
Just a note on the 'Sharing and Printing' section: we should just call it 'Sharing' because we eliminated the Print function.
