### ISSUE TITLE
Changed link to apply - Public Safety Officers' Death Benefits and Educational Assistance Program

### ISSUE THREAD

**Issue by diegocob** [GSA/px-bears-drupal#608]

**Comment by diegocob** [comment]
@erniedeeb, flagging that I changed the link to apply for this benefit from a pdf: https://psob.bja.ojp.gov/PSOB_FactSheet2019.pdf 

To this link: https://bja.ojp.gov/program/psob/benefits

Please double check it's ok. Want to avoid havig pdf links which may change and not have the most updated info.

**Comment by erniedeeb** [comment]
LGTM. It looks like it wasn't fully updated in the content bank though.

**Comment by diegocob** [comment]
Great. It looks updated on the [V2-Content Data Bank-BEARS-2023-07-25](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit?usp=sharing). Were you looking at the doc we used for the content review? I had duplicated the file for reviewing. Lm if this looks good.
