### ISSUE TITLE
Adding Questions to DOLO: Income, Disability, High School Diploma

### ISSUE THREAD

**Issue by diegocob** [GSA/px-bears-drupal#614]

**Comment by diegocob** [comment]
Three benefits require the eligibility question: "Do you have limited income and resources" but it's not currently on the form. Should we include it in the first page of q's?

@erniedeeb @fongcindy

**Comment by erniedeeb** [comment]
Which three questions? 

At a glance the income limit may be different for different benefits, which means we might want to omit it for now rather that introduce additional complexity to the forms and criteria.

**Comment by diegocob** [comment]
As I understand it, it's only one question linked to one criteria "Do you have limited income and resources?" and it's used for 9 benefits, 3 of which are in Dolo.

**Comment by diegocob** [comment]
@erniedeeb, just flagged that bc the disability question is not answered there are three benefits that are not being displayed. 

Suggesting adding the disability question to DOLO also. What do you think? I think we are still not overdoing it with the questions and the form is pretty light.

**Comment by diegocob** [comment]
This list keeps getting longer but...there is another question linked with disability and two related benefits: Are you unable to work for a year or more because of a disability, or your disability is expected to result in death?

What this last question and only display it if the person says they have a disability. That way we are only displaying two extra questions for the majority of the users.

**Comment by diegocob** [comment]
Flagging to @gchi25 and @scottqueen-bixal that we may add other questions to the form, one of which is branched.

**Comment by diegocob** [comment]
@erniedeeb, the Education benefits (GI Bill) for survivors is linked to a question that is not listed on DOLO: 
"Do you have a high-school diploma, GED certificate, or its equivalent?"

Otherwise even if somene meets the other four criteria, the benefit is not showing up as eligible:
![image](https://github.com/GSA/px-bears-drupal/assets/125094772/91cd345e-ba30-4982-8c34-003a723a0124)

See the Education benefits in the form here:

**Comment by erniedeeb** [comment]
Can we show this as eligible if the other 4 criteria are met? v1 did not have the education question, and seeing as this is the only (?) benefit that requires that criteria, I don't think it's worth adding a question. 

I would say let's keep the criteria under "more information needed" to help eligible users understand that they'll need to meet that additional qualification in the VA application process.

**Comment by diegocob** [comment]
As I understood it, the code logic is that if something is if there is information missing about that criteria (whether a question is left blank or there isn't a question on that form linked to that criteria) it will show up as more information needed.

@scottqueen-bixal and @gchi25, is there a way to show benefits that have all answered criteria MET show as eligible, EVEN if they more information is needed? For example, met 3 of 4 criteria and one criteria is needed?

**Comment by diegocob** [comment]
Deleted Income, disability, and high school diploma criteria from the benefits and added it in the summary of the benefit.

**Comment by diegocob** [comment]
Right now, if someone answers no to having served in the Armed forces the branched military questions do not appear and show up as more information needed. @scottqueen-bixal, could these autamatically be marked as "not met" instead of more info needed since it can be confusing for people that did not see that criteria.

**Comment by diegocob** [comment]
I understand we'll leave this for post-mvp
