### ISSUE TITLE
Design QA Last Items for Beta v2

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-bears-drupal#693]
As discussed, please change the following items, based on Ernesto's comments

1. Change the banner and form background blue color to a darker navy; Officer's Navy:162E51
2. Radio button bubbles, when selected should be changed from black to blue
3. Continue and Back CTA buttons on the bottom of the page need to be switched. Please change to the following "back" is on the left, "continue" is on the right. 

-

1-Officer blue
![Image](https://github.com/GSA/px-bears-drupal/assets/128498116/cf67bfee-bcee-4df3-bc3d-0fffa8614fc5)

2-Radio button bubbles
![Image](https://github.com/GSA/px-bears-drupal/assets/128498116/ee721ef0-0b56-4d90-b869-3086937ea151)

3-Continue and Back buttons
![Image](https://github.com/GSA/px-bears-drupal/assets/128498116/b15762e3-fb57-40c7-a4cb-c1db023704e7)

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @gscottqueen 
Hi guys,
Please let me know if you need my help with these.
Thank you!
Ernesto

**Comment by scottqueen-bixal** [comment]
Updates are on sandbox https://bears-waf.app.cloud.gov/benefit-finder/death

Change the banner and form background blue color to a darker navy; Officer's Navy:162E51


![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/8d59a764-d34e-4e0a-8fd0-592b2c312ebd)
![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/06b98b69-b09c-4a16-bd7e-eb1b245094c9)
![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/294aa081-ed88-42cb-a1da-421c5bbeeb31)



Radio button bubbles, when selected should be changed from black to blue


![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/136db0cc-e9f9-4ad0-8232-6f0ab6bf1a10)



Continue and Back CTA buttons on the bottom of the page need to be switched. Please change to the following "back" is on the left, "continue" is on the right.


![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/fe034918-be16-41a1-a599-00eb24a2f716)

add bottom margin to hints on fieldsets


![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/81a5d148-93da-4a22-8db8-31a6465c2c52)

**Comment by ErnestoFernandezAlvarez** [comment]
Thanks for the update @scottqueen-bixal !
