### ISSUE TITLE
Date and some eligibility criteria not working for some benefits (Covid scenario)

### ISSUE THREAD

**Issue by diegocob** [GSA/px-bears-drupal#695]
### Description

When running the [Covid persona scenario]([https://bears-waf.app.cloud.gov/benefit-finder/death?applicant_date_of_birth=%7B%22month%22%3A%223%22%2C%22day%22%3A%225%22%2C%22year%22%3A%221960%22%7D&applicant_relationship_to_the_deceased=Spouse&applicant_marital_status=Widowed&applicant_citizen_status=Yes&applicant_care_for_child=Yes&applicant_paid_funeral_expenses=Yes&deceased_date_of_death=%7B%22month%22%3A%221%22%2C%22day%22%3A%223%22%2C%22year%22%3A%222022%22%7D&deceased_death_location_is_US=Yes&deceased_paid_into_SS=Yes&deceased_public_safety_officer=No&deceased_miner=No&deceased_american_indian=No&deceased_died_of_COVID=Yes&deceased_served_in_active_military=No&shared=true'](https://bears-waf.app.cloud.gov/benefit-finder/death?applicant_date_of_birth=%7B%22month%22%3A%223%22%2C%22day%22%3A%225%22%2C%22year%22%3A%221960%22%7D&applicant_relationship_to_the_deceased=Spouse&applicant_marital_status=Widowed&applicant_citizen_status=Yes&applicant_care_for_child=Yes&applicant_paid_funeral_expenses=Yes&deceased_date_of_death=%7B%22month%22%3A%221%22%2C%22day%22%3A%223%22%2C%22year%22%3A%222022%22%7D&deceased_death_location_is_US=Yes&deceased_paid_into_SS=Yes&deceased_public_safety_officer=No&deceased_miner=No&deceased_american_indian=No&deceased_died_of_COVID=Yes&deceased_served_in_active_military=No&shared=true%27)) the date and other eligibility criteria for these benefits needs fixing: 

This is the link to the persona and answers: [https://bears-waf.app.cloud.gov/benefit-finder/death?applicant_date_of_birth=%7B%22month%22%3A%223%22%2C%22day%22%3A%225%22%2C%22year%22%3A%221960%22%7D&applicant_relationship_to_the_deceased=Spouse&applicant_marital_status=Widowed&applicant_citizen_status=Yes&applicant_care_for_child=Yes&applicant_paid_funeral_expenses=Yes&deceased_date_of_death=%7B%22month%22%3A%221%22%2C%22day%22%3A%223%22%2C%22year%22%3A%222022%22%7D&deceased_death_location_is_US=Yes&deceased_paid_into_SS=Yes&deceased_public_safety_officer=No&deceased_miner=No&deceased_american_indian=No&deceased_died_of_COVID=Yes&deceased_served_in_active_military=No&shared=true'](https://bears-waf.app.cloud.gov/benefit-finder/death?applicant_date_of_birth=%7B%22month%22%3A%223%22%2C%22day%22%3A%225%22%2C%22year%22%3A%221960%22%7D&applicant_relationship_to_the_deceased=Spouse&applicant_marital_status=Widowed&applicant_citizen_status=Yes&applicant_care_for_child=Yes&applicant_paid_funeral_expenses=Yes&deceased_date_of_death=%7B%22month%22%3A%221%22%2C%22day%22%3A%223%22%2C%22year%22%3A%222022%22%7D&deceased_death_location_is_US=Yes&deceased_paid_into_SS=Yes&deceased_public_safety_officer=No&deceased_miner=No&deceased_american_indian=No&deceased_died_of_COVID=Yes&deceased_served_in_active_military=No&shared=true%27) (for some reason this link was not hyperlinking).

1. [Annuity for certain military surviving spouses](https://bears-waf.app.cloud.gov/benefits/benefit/forgotten_widows_annuity_DOD)

Date of death eligibility should apply if the person died before 1978. 
I entered the date of death in 2/3/2022 and it said it met the criteria, which should not apply.
![image](https://github.com/GSA/px-bears-drupal/assets/125094772/df02d956-4563-4bab-b332-1ae7ad3abedb)

3. Date eligibility criteria not working for [COVID-19 funeral assistance](https://bears-waf.app.cloud.gov/benefits/benefit/covid_19_funeral_assistance_FEMA). 

Entered DOD was on 2/3/2022, which is after 5/20/2020 and the criteria should be met.
 Yet, the criteria shows not met. 

3a. When I enter the death was related to Covid 19, criteria should be met.
![image](https://github.com/GSA/px-bears-drupal/assets/125094772/cf74896f-6df8-4b14-8ff9-f016a50ca992)

4. Eligibility of date of death for [Lump-sum death benefit](https://bears-waf.app.cloud.gov/benefits/benefit/lump_sum_death_benefit_SSA) does not seem to be working. 

The DOD eligibility should apply if the death happened within the last two years.
I entered DOD was 2/3/2022 but shows not eligible.

![image](https://github.com/GSA/px-bears-drupal/assets/125094772/d1a2b3a6-d5a4-4cb3-99a7-0fdcc53c8451)

5. DOB eligibility for [Survivors pension for child with disabilities](https://bears-waf.app.cloud.gov/benefits/benefit/survivor_pension_child_disabled_VA) not working.

Eligibility should only be for applicants under 18 years.

Entered DOB 4/5/1960, 63 years of age, and the eligibility of under 18 years shows met.

![image](https://github.com/GSA/px-bears-drupal/assets/125094772/219c0f4b-f1a5-4f8a-a077-e22b5693eb24)

6. DOD eligibility for [Veterans burial allowance](https://bears-waf.app.cloud.gov/benefits/benefit/burial_allowance_VA) does not seem to be working.

Entered deceased died within the last two years 2/3/22 but the criteria was unmet.
https://bears-waf.app.cloud.gov/benefits/benefit/burial_allowance_VA

### User Story

Benefits should display criteria according to the answers met and benefit criteria.

**Comment by diegocob** [comment]
Cindy requested me to lump all these tix together.

**Comment by fongcindy** [comment]
Hi Diego, Scott and I reviewed each of the issues you identified. It looks like on the recent version of the MVP, the criteria's are displaying correctly in the accordion results. 

For the Date of death eligibility for the "annuity for certain military surviving spouse", Scott has fixed the issue (#713 ). Waiting for it to be ready for review in sandbox.

**Comment by diegocob** [comment]
Hi @scottqueen-bixal the Covid-19 benefit criteria of having died after May 20th 2020 still does not seem to be working. I tried it with the [veteran scenario](https://bears-waf.app.cloud.gov/benefit-finder/death?applicant_date_of_birth=%7B%22month%22%3A%220%22%2C%22day%22%3A%221%22%2C%22year%22%3A%221950%22%7D&applicant_relationship_to_the_deceased=Parent&applicant_marital_status=Married&applicant_citizen_status=Yes&applicant_care_for_child=No&applicant_paid_funeral_expenses=Yes&deceased_date_of_death=%7B%22month%22%3A%221%22%2C%22day%22%3A%222%22%2C%22year%22%3A%222022%22%7D&deceased_death_location_is_US=Yes&deceased_paid_into_SS=Yes&deceased_public_safety_officer=No&deceased_miner=No&deceased_american_indian=No&deceased_died_of_COVID=No&deceased_served_in_active_military=Yes&deceased_service_status=Active-duty%20service%20member&deceased_military_death_circumstance=Died%20while%20on%20active%20duty&deceased_grave_headstone=Yes&shared=true) and it didn't show eligible when it should have:

**Comment by scottqueen-bixal** [comment]
@diegocob try clearing cache or in an incognito tab, also

**Comment by scottqueen-bixal** [comment]
Survivors pension for child with disabilities is a content entry error, https://bears-waf.app.cloud.gov/benefits/benefit/survivor_pension_child_disabled_VA shows the acceptable value as 

Criteria Key
[Applicant date of birth](https://bears-waf.app.cloud.gov/benefits/criteria/applicant_date_of_birth)
Label
You are under 18 years
Acceptable Values
>18years

5 of the other 6 under 18 evaluations are working as expected



![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/936cae6f-5a85-45eb-8ada-0be23cb7eeec)

**Comment by fongcindy** [comment]
Scott and I have reviewed the scenario & eligibility criteria's on the English site, confirming it is functioning properly.

**Next steps:**
11/6: Diego, Ernesto, & Enrique are starting Spanish QA for this COVID scenario to check that the Spanish site and results match the English results and that the Spanish site is functioning properly. If there is time, can manually enter the values (from this scenarios [doc](https://docs.google.com/spreadsheets/d/1tCNJzKcQQvspkw2j30kkkv_XVFzghMXYEEd_SKSExq8/edit#gid=0)) to check the site and questions etc. 

Can flag issues here, but if there are a lot of issues: please create one new ticket to capture issues.

**Comment by diegocob** [comment]
I completed my audit and seems to be working fine.

- [ ] Correct amount of eligible benefits displayed
- [ ] Correct amount of not eligible benfits displayed
- [ ] Total eligible and not eligible benefits add to 33 total benefits
- [ ] All benefits criteria displayed correctly
- [ ] All titles are in sentence case
- [ ] All summary and eligibility text reads correctly in plain language
