### ISSUE TITLE
Review TSP benefit criteria

### ISSUE THREAD

**Issue by diegocob** [GSA/px-bears-drupal#90]
Received this comment: 

> TSP is not related to DOD, and I am of course eligible for TSP as I’ve been paying into it for 30 years. 
> 
> Do you flirt the same result? Thanks. 

In the retirement LE, we are saying TSP is administered by Department of Defense. This is technically incorrect, as TSP is administered by Federal Retirement Thrift Investment Board.

Though military service is required for a user to qualify for this benefit, we should think of a better way to explain that, as well as indicating that this benefit is also available for federal employees.

![Image](https://github.com/GSA/px-bears-drupal/assets/125094772/58b7905a-e710-49c1-a79c-e44c336b7a11)

**Comment by EnriqueOrt** [comment]
Content update to be made on the move from V1 to V2. 
Wording clarity - indicating that it is available for Fed employees.

**Comment by diegocob** [comment]
These two changes were made: 
1. Benefit Summary from:
- v1: The Thrift Savings Plan (TSP) is a Federal Government-sponsored retirement savings and investment plan available to members of the uniformed services.
- v2: A Federal Government-sponsored retirement savings and investment plan for members of the uniformed services **and federal employees.**
2. Providing Agency
- v1: Department of Defense
- v2: Federal Retirement Thrift Investment Board (FRTIB)
